text1 = str(input("Digite alguma palavra: "))
print('')
text2 = str(input("Digite alguma palavra: "))
print('')
print(f'você digitou, {text1}')
print('')
print(f'você tambem digitou, {text2}')
t = len(text1)
t1 = len(text2)
print('')
print(f'A primeira palavra que você digitou tem {t} letras')
print('')
print(f'segunda palavra que você digitou tem {t1} letras')
if (t != t1):
  print('')
  print("As duas strings são de tamanhos diferentes.")
if (text1 != text2):
  print('')
  print("As duas stings possuem conteúdo diferente.")
  print('')
